defmodule PersonalWebsite.BusTest do
  use ExUnit.Case, async: true

  alias PersonalWebsite.Bus

  @example_response """
  {
    "ver":"1.33",
    "lang":"deu",
    "id":"gwiqupd46q8z84ww",
    "err":"OK",
    "graph":{
      "id":"standard",
      "index":0
    },
    "subGraph":{
      "id":"global",
      "index":0
    },
    "view":{
      "id":"standard",
      "index":0,
      "type":"WGS84"
    },
    "svcResL":[
      {
        "id":"1|1|",
        "meth":"StationBoard",
        "err":"OK",
        "res":{
          "common":{
            "locL":[
              {
                "lid":"A=1@O=Lückhoffstr. (Berlin)@X=13206682@Y=52434016@U=86@L=900052253@",
                "type":"S",
                "name":"Lückhoffstr. (Berlin)",
                "icoX":2,
                "extId":"900052253",
                "state":"F",
                "crd":{
                  "x":13206682,
                  "y":52434016,
                  "floor":0
                },
                "pCls":8,
                "pRefL":[
                  1,
                  2
                ],
                "gidL":[
                  "A×de:11000:900052253"
                ]
              },
              {
                "lid":"A=1@O=S Nikolassee (Berlin)@X=13193297@Y=52431212@U=86@L=900052201@",
                "type":"S",
                "name":"S Nikolassee (Berlin)",
                "icoX":2,
                "extId":"900052201",
                "state":"F",
                "crd":{
                  "x":13193297,
                  "y":52431212,
                  "floor":0
                },
                "pCls":9,
                "gidL":[
                  "A×de:11000:900052201"
                ]
              },
              {
                "lid":"A=1@O=Nahmitzer Damm (Berlin)@X=13366384@Y=52410698@U=86@L=900073305@",
                "type":"S",
                "name":"Nahmitzer Damm (Berlin)",
                "icoX":2,
                "extId":"900073305",
                "state":"F",
                "crd":{
                  "x":13366384,
                  "y":52410698,
                  "floor":0
                },
                "pCls":8,
                "gidL":[
                  "A×de:11000:900073305"
                ]
              }
            ],
            "prodL":[
              {
                "pid":"L::3::Bus::B3041857784::Bus_3041857784_112::*",
                "name":"112",
                "nameS":"112",
                "number":"112",
                "icoX":0,
                "cls":8,
                "oprX":0,
                "prodCtx":{
                  "name":"     112",
                  "num":"12636",
                  "line":"112",
                  "matchId":"112",
                  "catOut":"Bus     ",
                  "catOutS":"B",
                  "catOutL":"Bus     ",
                  "catIn":"B",
                  "catCode":"3",
                  "admin":"BVB---"
                },
                "himIdL":[
                  "HIM_FREETEXT_75748",
                  "HIM_FREETEXT_81700",
                  "HIM_FREETEXT_85225"
                ]
              },
              {
                "name":"112",
                "nameS":"112",
                "icoX":0,
                "cls":8,
                "prodCtx":{
                  "name":"112",
                  "line":"112",
                  "lineId":"112",
                  "catOut":"Bus     ",
                  "catOutS":"B",
                  "catOutL":"Bus     "
                }
              },
              {
                "name":"N18",
                "nameS":"N18",
                "icoX":0,
                "cls":8,
                "prodCtx":{
                  "name":"N18",
                  "line":"N18",
                  "lineId":"N18",
                  "catOut":"Bus     ",
                  "catOutS":"B",
                  "catOutL":"Bus     "
                }
              },
              {
                "pid":"L::3::Bus::B3041857784::Bus_3041857784_112::*",
                "name":"112",
                "nameS":"112",
                "number":"112",
                "icoX":0,
                "cls":8,
                "oprX":0,
                "prodCtx":{
                  "name":"     112",
                  "num":"12608",
                  "line":"112",
                  "matchId":"112",
                  "catOut":"Bus     ",
                  "catOutS":"B",
                  "catOutL":"Bus     ",
                  "catIn":"B",
                  "catCode":"3",
                  "admin":"BVB---"
                },
                "himIdL":[
                  "HIM_FREETEXT_75748",
                  "HIM_FREETEXT_81700",
                  "HIM_FREETEXT_85225"
                ]
              }
            ],
            "opL":[
              {
                "name":"Berliner Verkehrsbetriebe",
                "icoX":1,
                "id":"Berliner Verkehrsbetriebe"
              }
            ],
            "remL":[
              {
                "type":"A",
                "code":"OPERATOR",
                "icoX":3,
                "txtS":"BVG",
                "txtN":"BVG",
                "txtL":"Berliner Verkehrsbetriebe"
              },
              {
                "type":"A",
                "code":"bf",
                "prio":2,
                "icoX":3,
                "txtN":"barrierefrei"
              }
            ],
            "himL":[
              {
                "hid":"81700",
                "act":true,
                "head":"Kein Vordereinstieg bei vielen Bussen",
                "text":"Fahrscheine erhalten Sie über die Fahrinfo- oder Ticket-App (www.bvg.de/apps) und im Vorverkauf.",
                "icoX":4,
                "prio":100,
                "prod":65535,
                "src":50,
                "lModDate":"20200814",
                "lModTime":"111600",
                "sDate":"20200810",
                "sTime":"033000",
                "eDate":"20201212",
                "eTime":"000000",
                "sDaily":"000000",
                "eDaily":"235900",
                "comp":"BVG",
                "catRefL":[
                  0
                ],
                "pubChL":[
                  {
                    "name":"TIMETABLE",
                    "fDate":"20200811",
                    "fTime":"125500",
                    "tDate":"20201212",
                    "tTime":"000000"
                  }
                ]
              },
              {
                "hid":"85225",
                "act":true,
                "head":"Gemeinsam gegen Corona: Abstand halten, Mund und Nase bedecken!",
                "text":"In Bahnhöfen und Fahrzeugen ist es Pflicht, Mund und Nase zu bedecken. Maskenmuffel riskieren mindestens 50 Euro. Info: bvg.de/corona",
                "icoX":4,
                "prio":100,
                "prod":65535,
                "src":50,
                "lModDate":"20200716",
                "lModTime":"094118",
                "sDate":"20200427",
                "sTime":"000000",
                "eDate":"20201212",
                "eTime":"000000",
                "sDaily":"000000",
                "eDaily":"235900",
                "comp":"BVG",
                "catRefL":[
                  0
                ],
                "pubChL":[
                  {
                    "name":"TIMETABLE",
                    "fDate":"20200427",
                    "fTime":"000000",
                    "tDate":"20201231",
                    "tTime":"235900"
                  }
                ]
              }
            ],
            "icoL":[
              {
                "res":"prod_bus_t",
                "fg":{
                  "r":255,
                  "g":255,
                  "b":255
                },
                "bg":{
                  "r":166,
                  "g":22,
                  "b":128,
                  "a":255
                }
              },
              {
                "res":"BVG",
                "txt":"Berliner Verkehrsbetriebe"
              },
              {
                "res":"STA"
              },
              {
                "res":"INFO"
              },
              {
                "res":"HIM0"
              }
            ],
            "himMsgCatL":[
              {
                "id":0
              }
            ],
            "lDrawStyleL":[
              {
                "sIcoX":0,
                "type":"SOLID",
                "bg":{
                  "r":166,
                  "g":22,
                  "b":128,
                  "a":255
                }
              },
              {
                "type":"SOLID",
                "bg":{
                  "r":166,
                  "g":22,
                  "b":128,
                  "a":255
                }
              }
            ]
          },
          "type":"DEP",
          "jnyL":[
            {
              "jid":"1|6608|5|86|19082020",
              "date":"20200819",
              "prodX":0,
              "dirTxt":"S Nikolassee",
              "dirFlg":"2",
              "status":"P",
              "isRchbl":true,
              "stbStop":{
                "locX":0,
                "idx":34,
                "dProdX":0,
                "dTimeS":"094800",
                "dTimeR":"094700",
                "dProgType":"PROGNOSED",
                "type":"N"
              },
              "msgL":[
                {
                  "type":"REM",
                  "remX":0,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_DTL"
                  ]
                },
                {
                  "type":"REM",
                  "remX":1,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_DTL_H3"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":0,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":1,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                }
              ],
              "subscr":"F",
              "prodL":[
                {
                  "prodX":0,
                  "fLocX":0,
                  "tLocX":1,
                  "fIdx":34,
                  "tIdx":39
                }
              ],
              "sumLDrawStyleX":0,
              "resLDrawStyleX":1,
              "trainStartDate":"20200819"
            },
            {
              "jid":"1|6580|1|86|19082020",
              "date":"20200819",
              "prodX":3,
              "dirTxt":"Lichterfelde, Lindenstr.",
              "dirFlg":"1",
              "status":"P",
              "isRchbl":true,
              "stbStop":{
                "locX":0,
                "idx":2,
                "dProdX":3,
                "dTimeS":"095800",
                "dTimeR":"095800",
                "dProgType":"PROGNOSED",
                "type":"N"
              },
              "msgL":[
                {
                  "type":"REM",
                  "remX":0,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_DTL"
                  ]
                },
                {
                  "type":"REM",
                  "remX":1,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_DTL_H3"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":0,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":1,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                }
              ],
              "subscr":"F",
              "prodL":[
                {
                  "prodX":3,
                  "fLocX":0,
                  "tLocX":2,
                  "fIdx":2,
                  "tIdx":37
                }
              ],
              "sumLDrawStyleX":0,
              "resLDrawStyleX":1,
              "trainStartDate":"20200819"
            },
            {
              "jid":"1|6608|6|86|19082020",
              "date":"20200819",
              "prodX":0,
              "dirTxt":"S Nikolassee",
              "dirFlg":"2",
              "status":"P",
              "isRchbl":true,
              "stbStop":{
                "locX":0,
                "idx":34,
                "dProdX":0,
                "dTimeS":"100800",
                "dTimeR":"100800",
                "dProgType":"PROGNOSED",
                "type":"N"
              },
              "msgL":[
                {
                  "type":"REM",
                  "remX":0,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_DTL"
                  ]
                },
                {
                  "type":"REM",
                  "remX":1,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_DTL_H3"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":0,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":1,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                }
              ],
              "subscr":"F",
              "prodL":[
                {
                  "prodX":0,
                  "fLocX":0,
                  "tLocX":1,
                  "fIdx":34,
                  "tIdx":39
                }
              ],
              "sumLDrawStyleX":0,
              "resLDrawStyleX":1,
              "trainStartDate":"20200819"
            },
            {
              "jid":"1|6580|2|86|19082020",
              "date":"20200819",
              "prodX":3,
              "dirTxt":"Marienfelde, Nahmitzer Damm",
              "dirFlg":"1",
              "status":"P",
              "isRchbl":true,
              "stbStop":{
                "locX":0,
                "idx":2,
                "dProdX":3,
                "dTimeS":"101800",
                "dTimeR":"101800",
                "dProgType":"PROGNOSED",
                "type":"N"
              },
              "msgL":[
                {
                  "type":"REM",
                  "remX":0,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_DTL"
                  ]
                },
                {
                  "type":"REM",
                  "remX":1,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_DTL_H3"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":0,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":1,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                }
              ],
              "subscr":"F",
              "prodL":[
                {
                  "prodX":3,
                  "fLocX":0,
                  "tLocX":2,
                  "fIdx":2,
                  "tIdx":37
                }
              ],
              "sumLDrawStyleX":0,
              "resLDrawStyleX":1,
              "trainStartDate":"20200819"
            },
            {
              "jid":"1|6608|7|86|19082020",
              "date":"20200819",
              "prodX":0,
              "dirTxt":"S Nikolassee",
              "dirFlg":"2",
              "status":"P",
              "isRchbl":true,
              "stbStop":{
                "locX":0,
                "idx":34,
                "dProdX":0,
                "dTimeS":"102800",
                "type":"N"
              },
              "msgL":[
                {
                  "type":"REM",
                  "remX":0,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_DTL"
                  ]
                },
                {
                  "type":"REM",
                  "remX":1,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_DTL_H3"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":0,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":1,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                }
              ],
              "subscr":"F",
              "prodL":[
                {
                  "prodX":0,
                  "fLocX":0,
                  "tLocX":1,
                  "fIdx":34,
                  "tIdx":39
                }
              ],
              "sumLDrawStyleX":0,
              "resLDrawStyleX":1,
              "trainStartDate":"20200819"
            },
            {
              "jid":"1|6580|3|86|19082020",
              "date":"20200819",
              "prodX":3,
              "dirTxt":"Marienfelde, Nahmitzer Damm",
              "dirFlg":"1",
              "status":"P",
              "isRchbl":true,
              "stbStop":{
                "locX":0,
                "idx":2,
                "dProdX":3,
                "dTimeS":"103800",
                "type":"N"
              },
              "msgL":[
                {
                  "type":"REM",
                  "remX":0,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_DTL"
                  ]
                },
                {
                  "type":"REM",
                  "remX":1,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_DTL_H3"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":0,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":1,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                }
              ],
              "subscr":"F",
              "prodL":[
                {
                  "prodX":3,
                  "fLocX":0,
                  "tLocX":2,
                  "fIdx":2,
                  "tIdx":37
                }
              ],
              "sumLDrawStyleX":0,
              "resLDrawStyleX":1,
              "trainStartDate":"20200819"
            },
            {
              "jid":"1|6608|8|86|19082020",
              "date":"20200819",
              "prodX":0,
              "dirTxt":"S Nikolassee",
              "dirFlg":"2",
              "status":"P",
              "isRchbl":true,
              "stbStop":{
                "locX":0,
                "idx":34,
                "dProdX":0,
                "dTimeS":"104800",
                "dTimeR":"104800",
                "dProgType":"PROGNOSED",
                "type":"N"
              },
              "msgL":[
                {
                  "type":"REM",
                  "remX":0,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_DTL"
                  ]
                },
                {
                  "type":"REM",
                  "remX":1,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_DTL_H3"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":0,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":1,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                }
              ],
              "subscr":"F",
              "prodL":[
                {
                  "prodX":0,
                  "fLocX":0,
                  "tLocX":1,
                  "fIdx":34,
                  "tIdx":39
                }
              ],
              "sumLDrawStyleX":0,
              "resLDrawStyleX":1,
              "trainStartDate":"20200819"
            },
            {
              "jid":"1|6580|4|86|19082020",
              "date":"20200819",
              "prodX":3,
              "dirTxt":"Marienfelde, Nahmitzer Damm",
              "dirFlg":"1",
              "status":"P",
              "isRchbl":true,
              "stbStop":{
                "locX":0,
                "idx":2,
                "dProdX":3,
                "dTimeS":"105800",
                "type":"N"
              },
              "msgL":[
                {
                  "type":"REM",
                  "remX":0,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_DTL"
                  ]
                },
                {
                  "type":"REM",
                  "remX":1,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_DTL_H3"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":0,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":1,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                }
              ],
              "subscr":"F",
              "prodL":[
                {
                  "prodX":3,
                  "fLocX":0,
                  "tLocX":2,
                  "fIdx":2,
                  "tIdx":37
                }
              ],
              "sumLDrawStyleX":0,
              "resLDrawStyleX":1,
              "trainStartDate":"20200819"
            },
            {
              "jid":"1|6608|9|86|19082020",
              "date":"20200819",
              "prodX":0,
              "dirTxt":"S Nikolassee",
              "dirFlg":"2",
              "status":"P",
              "isRchbl":true,
              "stbStop":{
                "locX":0,
                "idx":34,
                "dProdX":0,
                "dTimeS":"110800",
                "dTimeR":"110800",
                "dProgType":"PROGNOSED",
                "type":"N"
              },
              "msgL":[
                {
                  "type":"REM",
                  "remX":0,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_DTL"
                  ]
                },
                {
                  "type":"REM",
                  "remX":1,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_DTL_H3"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":0,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":1,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                }
              ],
              "subscr":"F",
              "prodL":[
                {
                  "prodX":0,
                  "fLocX":0,
                  "tLocX":1,
                  "fIdx":34,
                  "tIdx":39
                }
              ],
              "sumLDrawStyleX":0,
              "resLDrawStyleX":1,
              "trainStartDate":"20200819"
            },
            {
              "jid":"1|6580|5|86|19082020",
              "date":"20200819",
              "prodX":3,
              "dirTxt":"Marienfelde, Nahmitzer Damm",
              "dirFlg":"1",
              "status":"P",
              "isRchbl":true,
              "stbStop":{
                "locX":0,
                "idx":2,
                "dProdX":3,
                "dTimeS":"111800",
                "type":"N"
              },
              "msgL":[
                {
                  "type":"REM",
                  "remX":0,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_DTL"
                  ]
                },
                {
                  "type":"REM",
                  "remX":1,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_DTL_H3"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":0,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":1,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                }
              ],
              "subscr":"F",
              "prodL":[
                {
                  "prodX":3,
                  "fLocX":0,
                  "tLocX":2,
                  "fIdx":2,
                  "tIdx":37
                }
              ],
              "sumLDrawStyleX":0,
              "resLDrawStyleX":1,
              "trainStartDate":"20200819"
            },
            {
              "jid":"1|6608|10|86|19082020",
              "date":"20200819",
              "prodX":0,
              "dirTxt":"S Nikolassee",
              "dirFlg":"2",
              "status":"P",
              "isRchbl":true,
              "stbStop":{
                "locX":0,
                "idx":34,
                "dProdX":0,
                "dTimeS":"112800",
                "dTimeR":"112800",
                "dProgType":"PROGNOSED",
                "type":"N"
              },
              "msgL":[
                {
                  "type":"REM",
                  "remX":0,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_DTL"
                  ]
                },
                {
                  "type":"REM",
                  "remX":1,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_DTL_H3"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":0,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":1,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":1,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                }
              ],
              "subscr":"F",
              "prodL":[
                {
                  "prodX":0,
                  "fLocX":0,
                  "tLocX":1,
                  "fIdx":34,
                  "tIdx":39
                }
              ],
              "sumLDrawStyleX":0,
              "resLDrawStyleX":1,
              "trainStartDate":"20200819"
            },
            {
              "jid":"1|6580|6|86|19082020",
              "date":"20200819",
              "prodX":3,
              "dirTxt":"Marienfelde, Nahmitzer Damm",
              "dirFlg":"1",
              "status":"P",
              "isRchbl":true,
              "stbStop":{
                "locX":0,
                "idx":2,
                "dProdX":3,
                "dTimeS":"113800",
                "type":"N"
              },
              "msgL":[
                {
                  "type":"REM",
                  "remX":0,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_DTL"
                  ]
                },
                {
                  "type":"REM",
                  "remX":1,
                  "sty":"I",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_DTL_H3"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":0,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                },
                {
                  "type":"HIM",
                  "himX":1,
                  "sty":"M",
                  "fLocX":0,
                  "tLocX":2,
                  "tagL":[
                    "RES_JNY_H1"
                  ]
                }
              ],
              "subscr":"F",
              "prodL":[
                {
                  "prodX":3,
                  "fLocX":0,
                  "tLocX":2,
                  "fIdx":2,
                  "tIdx":37
                }
              ],
              "sumLDrawStyleX":0,
              "resLDrawStyleX":1,
              "trainStartDate":"20200819"
            }
          ],
          "fpB":"20200809",
          "fpE":"20201212",
          "planrtTS":"1597823186",
          "sD":"20200819",
          "sT":"094702",
          "locRefL":[
            0
          ]
        }
      }
    ]
  }
  """

  describe "parse_results/1" do
    test "parses the results correctly" do
      assert {datetime, bus_times} = Bus.parse_results(@example_response)
      assert NaiveDateTime.compare(datetime, ~N[2020-08-19 09:47:02]) == :eq

      assert %{
               "← Zehlendorf" => [
                 ~T[09:58:00],
                 ~T[10:18:00],
                 ~T[10:38:00],
                 ~T[10:58:00],
                 ~T[11:18:00],
                 ~T[11:38:00]
               ],
               "→ S-Bahn" => [
                 ~T[09:47:00],
                 ~T[10:08:00],
                 ~T[10:28:00],
                 ~T[10:48:00],
                 ~T[11:08:00],
                 ~T[11:28:00]
               ]
             } == bus_times
    end
  end

  describe "request_data/0" do
    # This is just to make manual testing easier
    @tag :skip
    test "makes the right HTTP call" do
      IO.inspect(Bus.request_data())
    end
  end
end
